### ISSUE TITLE
write pdf

### ISSUE THREAD

**Issue by doubletaketech** [olafurjohannsson/htmltopdf#1]
How do you access the resulting pdf document in order to write it to fs?  I need the pdf saved to a specific location on the server.

Also, is the resulting PDF in Buffer data format?

Thanks,
Donnie

**Comment by olafurjohannsson** [comment]
To save the PDF to a specific location you pass the path as a arguments as so;

**htmltopdf.createFromHtml(html, './dir/subdir/file.pdf', callback**

Then it will save the PDF on the specified location.

Yes, the PDF is in an image buffer that Phantom generates via it's render method

http://phantomjs.org/api/webpage/method/render.html

Unfortunately there is no way to access the PDF buffer in this particular version, hopefully i will add it at a later date.

**Comment by doubletaketech** [comment]
Thank you! I didn't realize you were already writing the file.  So, I don't really need access to the buffer to write it myself. 

Thank you!
Donnie
