### ISSUE TITLE
images?

### ISSUE THREAD

**Issue by doubletaketech** [olafurjohannsson/htmltopdf#2]
does it support images  in the template option? 
I need my pdf to contain thumbnails of photos. 
my little test doesn't show the image in the pdf.

 Or does it need to be a dataUrl instead of path?

**Comment by olafurjohannsson** [comment]
There is no support to include images unfortunately via it's source attribute.

The reason for this i am not sure, for some reason Phantom doesn't inject them into the resulting buffer.

You can however use dataurl as you mentioned, so you just have to convert the image to a base64 string 

```
var pdfName = 'test.pdf';
var html = '<html><img src="data:image/png;base64,{{img}}" alt="img"/></html>';
var data = {
    'img': fs.readFileSync('image.png').toString('base64')
};

htmltopdf.createFromTemplateData(html, data, pdfName, function (err, success) {
    // .. 
});
```

**Comment by doubletaketech** [comment]
Thank you! works good.  I'll need to test performance because I'll have 2-3 image thumbs per page and a lot of pages. 

Appreciate the help!
Donnie

**Comment by doubletaketech** [comment]
Images are working great now.  It doesn't seem to work to include bootstrap css in the template.  I tried adding the cdn url in the head.  Any way to include styles?

**Comment by olafurjohannsson** [comment]
Try using a style element and an import url tag

I'm importing this CSS file with one of the PDFs i'm creating

```
        <style media="screen, print">

            @import url(http://fonts.googleapis.com/css?family=Bree+Serif);
```

**Comment by doubletaketech** [comment]
Your google fonts imports works fine for me.  But not bootstrap. Must be something with Bootstrap CDN
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css 

maybe they require this crossorigin stuff
http://getbootstrap.com/getting-started/ 
I can't find anything on how to import specifically. 

not a big deal, I can just use my own css.  Bootstrap just makes it all easier.

Thanks for all your help.  PDF is looking good with images! 
Donnie

**Comment by olafurjohannsson** [comment]
Have you tried another CDN then maxcdn?

A workaround is also just copy/pasting the bootstrap minified source into your HTML file.

**Comment by doubletaketech** [comment]
I tried CDN, loading bootstrap off my server and pasting the min code inside.  Very strange, none of them work.  But any other css works fine. 
any idea why I get this overlap effect on page transitions?

<img width="824" alt="screen shot 2016-02-22 at 9 57 43 am" src="https://cloud.githubusercontent.com/assets/3866443/13223729/256c6c1e-d94b-11e5-8281-80946bc4acda.png">

**Comment by olafurjohannsson** [comment]
Hmm i find it very strange that it doesn't work copy pasting the minified CSS bootstrap.

Not sure about the transition, the resulting PDF is supposed to output A4 sizes as seen here https://github.com/olafurjohannsson/htmltopdf/blob/master/index.js#L36 

Which is 210mm × 297mm

**Comment by doubletaketech** [comment]
maybe it doesn't support media queries or something that is unique inside bootstrap's css.  Not too worried about that for now.  

My main issue now is the page transitions.  Might need something like a page break.  I'll see if I can handle it by adding some <br>'s to the template so that is is only one meter per page.

**Comment by doubletaketech** [comment]
I figured out a workaround. you only get the "doubling effect" if you have text in the bottom page margin area.  Adding <br> to avoid the very bottom fixes the issue. 

Appreciate all your help.
Donnie

**Comment by doubletaketech** [comment]
found a better solution (from Phantomjs) for inserting a page break. works in the handlebars template of htmltopdf . This avoids the doubling without having to add in the spacing. Nice :) 
`<div style="page-break-after:always;"> <!-- content --></div>`
